# Generated by Django 6.0.2 on 2026-02-18 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=10)),
                ('session_id', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot_slug', models.CharField(db_index=True, default='default', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('bot_slug', models.CharField(db_index=True, max_length=64)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('content', models.TextField()),
                ('categories', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('bot_slug', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(choices=[('chat', 'Chat'), ('memory', 'Memory'), ('summary', 'Summary'), ('moderation', 'Moderation')], max_length=16)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('bot_slug', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('preference', 'Préférence'), ('fact', 'Fait'), ('context', 'Contexte')], default='fact', max_length=16)),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=0.8)),
                ('source', models.CharField(choices=[('auto', 'Extraction automatique'), ('manual', 'Déclaration manuelle')], default='auto', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('user_uuid', 'bot_slug', 'key'), name='unique_anonymous_memory'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'bot_slug', 'key'), name='unique_authenticated_memory')],
            },
        ),
    ]
